### ISSUE TITLE
Single posts are not being created by react

### ISSUE THREAD

**Issue by low-bin** [jlengstorf/wordpress-jamstack#11]
First of all, thank you for making the project available.
I implemented my project by calling information from a Wordpress installed on my server at Godaddy. My interest is to use my Godaddy server for the Wordpress panel and host the Gatsby presentation layer on Netlify.
I managed to implement the local tutorial calling from my server, but in the part of displaying the Single posts the content is called by the on the blog page, but individually is not displayed.

![gatsby erro](https://user-images.githubusercontent.com/73001840/117090882-f75bf880-ad2f-11eb-8849-69852acd4818.PNG)

I forward the error image displayed in the browser as an attachment.
The terminal also displayed the error:
(node: 15552) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at
C: \ Users \ ... \ node_modules \ postcss \ package.json.
Update this package.json to use a subpath pattern like "./*".
Is there a relationship with the non-display of single posts?
Sorry, the question seems out of place, but I have no idea why this error is occurring.
Thank you for your attention

**Comment by jlengstorf** [comment]
hey, @low-bin — thanks for your patience here! I missed this in my sea of GitHub notifications

the issue appears to be a double slash in your code for creating pages (see the bottom, where it's showing `/blog//hello-world/` as a page that exists). most likely that extra slash is in your `gatsby-node.js`

hope that helps!
